# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdbapp', '0002_auto_20170127_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
