# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdbapp', '0003_auto_20170127_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor_Graph',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('json_data', models.TextField()),
            ],
        ),
    ]
