# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdbapp', '0004_actor_graph'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='birthday',
            field=models.CharField(default='1st January 1990', max_length=100),
        ),
    ]
